### ISSUE TITLE
Feature suggestions - Additional customization in responsive design.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd-plus#13]
What I am thinking about is ways to easily adjust various elements as the screen size becomes smaller. Responsive design and break points.

**Comment by aristath** [comment]
such as?

**Comment by paaljoachim** [comment]
For instance today we have the mobile break point. What about also having a tablet break point?

---

Or just skip any mention of the tablet break point in the customizer and instead add it to responsive docs. Showing how to use Media Queries..
I will create a few sites with the child theme I have created, and suggest a few things to add to the future doc.

**Comment by aristath** [comment]
> For instance today we have the mobile break point. What about also having a tablet break point?

Nope, multiple breakpoints are a horrible practice. I realize that it's the way we've been doing things in the web for years, but that doesn't mean we should perpetuate the same bad practices just because we're used to doing things that way.

> Or just skip any mention of the tablet break point in the customizer and instead add it to responsive docs. Showing how to use Media Queries..

I agree that we should add some useful snippets in the docs and we should explain some things.
However, there are some things that don't belong in the theme's docs. For example explaining **why** multiple breakpoints are bad, or educating users about what media-queries are and how they should write css. These things don't belong in the theme docs... The theme docs should only contain theme-specific snippets.

In regards to adding option I want to avoid adding as many options as possible...
I realize that other themes add a lot of options, but that's exactly what I want to avoid in Gridd.
Adding 10 options to customize a button for example is easy. It allows great customization, but introduces a **huge** amount of bload and makes it more difficult to do simple things.

**Comment by paaljoachim** [comment]
I am closing this issue for now.
